// Vehicle Makes and Models Database
export const VEHICLE_MAKES = [
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Citroen',
  'Daewoo',
  'Daihatsu',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'Geely',
  'Genesis',
  'GMC',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'Jaguar',
  'Jeep',
  'Kia',
  'Koenigsegg',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Maserati',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Pagani',
  'Peugeot',
  'Pontiac',
  'Porsche',
  'Ram',
  'Renault',
  'Rolls-Royce',
  'Saab',
  'Saturn',
  'Scion',
  'Seat',
  'Skoda',
  'Smart',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Other',
] as const;

export const VEHICLE_MODELS_BY_MAKE: Record<string, string[]> = {
  Toyota: [
    'Camry',
    'Corolla',
    'RAV4',
    'Highlander',
    'Tacoma',
    'Tundra',
    'Prius',
    'Sienna',
    'Avalon',
    'Land Cruiser',
    'Yaris',
    'C-HR',
    'Venza',
    'Other',
  ],
  Honda: [
    'Accord',
    'Civic',
    'CR-V',
    'Pilot',
    'Odyssey',
    'HR-V',
    'Ridgeline',
    'Passport',
    'Fit',
    'Insight',
    'Other',
  ],
  Ford: [
    'F-150',
    'Explorer',
    'Escape',
    'Mustang',
    'Edge',
    'Expedition',
    'Ranger',
    'Bronco',
    'Fusion',
    'Focus',
    'Fiesta',
    'Transit',
    'Other',
  ],
  Nissan: [
    'Altima',
    'Sentra',
    'Rogue',
    'Pathfinder',
    'Frontier',
    'Titan',
    'Maxima',
    'Versa',
    'Murano',
    'Armada',
    'Kicks',
    'Other',
  ],
  BMW: [
    '3 Series',
    '5 Series',
    '7 Series',
    'X1',
    'X3',
    'X5',
    'X7',
    'M3',
    'M5',
    'i3',
    'i4',
    'iX',
    'Other',
  ],
  'Mercedes-Benz': [
    'C-Class',
    'E-Class',
    'S-Class',
    'GLA',
    'GLC',
    'GLE',
    'GLS',
    'A-Class',
    'CLA',
    'AMG GT',
    'Other',
  ],
  Audi: ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'TT', 'R8', 'Other'],
  Volkswagen: [
    'Jetta',
    'Passat',
    'Golf',
    'Tiguan',
    'Atlas',
    'Arteon',
    'Taos',
    'ID.4',
    'Other',
  ],
  Hyundai: [
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Palisade',
    'Kona',
    'Venue',
    'Ioniq',
    'Other',
  ],
  Kia: [
    'Forte',
    'K5',
    'Optima',
    'Sportage',
    'Sorento',
    'Telluride',
    'Soul',
    'Seltos',
    'Carnival',
    'EV6',
    'Other',
  ],
  Mazda: ['Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-9', 'CX-30', 'CX-50', 'MX-5 Miata', 'Other'],
  Chevrolet: [
    'Silverado',
    'Equinox',
    'Traverse',
    'Malibu',
    'Tahoe',
    'Suburban',
    'Colorado',
    'Blazer',
    'Camaro',
    'Corvette',
    'Bolt',
    'Other',
  ],
  Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'Other'],
  Lexus: [
    'ES',
    'IS',
    'LS',
    'GS',
    'RX',
    'GX',
    'LX',
    'NX',
    'UX',
    'LC',
    'RC',
    'Other',
  ],
  Other: ['Other'],
};

// Generate years from 1990 to current year + 1
const currentYear = new Date().getFullYear();
export const VEHICLE_YEARS = Array.from({ length: currentYear - 1989 + 2 }, (_, i) =>
  (currentYear + 1 - i).toString()
);

// Spare Parts Categories
export const SPARE_PARTS_CATEGORIES = [
  'Engine Parts',
  'Transmission Parts',
  'Brake System',
  'Suspension & Steering',
  'Exhaust System',
  'Cooling System',
  'Fuel System',
  'Electrical System',
  'Body Parts',
  'Interior Parts',
  'Lighting',
  'Filters',
  'Belts & Hoses',
  'Batteries',
  'Tires & Wheels',
  'Windshield & Glass',
  'Fluids & Lubricants',
  'Tools & Equipment',
  'Vehicle Tracking Devices',
  'Accessories',
  'Other',
] as const;

// Common spare parts by category
export const COMMON_SPARE_PARTS: Record<string, string[]> = {
  'Engine Parts': [
    'Engine Oil',
    'Oil Filter',
    'Air Filter',
    'Spark Plugs',
    'Fuel Injectors',
    'Timing Belt',
    'Piston Rings',
    'Gaskets',
    'Valves',
    'Camshaft',
    'Crankshaft',
    'Other',
  ],
  'Brake System': [
    'Brake Pads',
    'Brake Rotors',
    'Brake Fluid',
    'Brake Calipers',
    'Brake Lines',
    'Master Cylinder',
    'Brake Drums',
    'Brake Shoes',
    'Other',
  ],
  'Suspension & Steering': [
    'Shock Absorbers',
    'Struts',
    'Control Arms',
    'Ball Joints',
    'Tie Rod Ends',
    'Steering Rack',
    'Power Steering Pump',
    'Wheel Bearings',
    'Sway Bar Links',
    'Other',
  ],
  'Electrical System': [
    'Battery',
    'Alternator',
    'Starter Motor',
    'Ignition Coil',
    'Fuses',
    'Relays',
    'Wiring Harness',
    'Sensors',
    'Other',
  ],
  Filters: [
    'Oil Filter',
    'Air Filter',
    'Fuel Filter',
    'Cabin Air Filter',
    'Transmission Filter',
    'Other',
  ],
  'Tires & Wheels': [
    'All-Season Tires',
    'Summer Tires',
    'Winter Tires',
    'Alloy Wheels',
    'Steel Wheels',
    'Wheel Nuts',
    'Valve Stems',
    'Other',
  ],
  'Vehicle Tracking Devices': [
    'Hardwired GPS Tracker',
    'OBD-II GPS Tracker',
    'Portable GPS Tracker',
    'Magnetic GPS Tracker',
    'GPS Antenna',
    'SIM Card for Tracker',
    'Other',
  ],
  Other: ['Other'],
};

// Helper function to get models for a make
export function getModelsForMake(make: string): string[] {
  return VEHICLE_MODELS_BY_MAKE[make] || ['Other'];
}

// Helper function to get parts for a category
export function getPartsForCategory(category: string): string[] {
  return COMMON_SPARE_PARTS[category] || ['Other'];
}
